### ISSUE TITLE
new update - crash if i enter 'ls'

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#26]
```
Python 3.8.10
Init: cuda_breadcrumbs
Loaded session: "history session.json", 20ms, 1 file(s)
Init: cuda_hilite_occurrences
Startup: 230ms, plugins: 30ms (breadcrumbs 28ms, hilite_occurrences 6ms)
Init: cuda_example_terminal
Init: cudatext
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 476, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 463, in get_hotkeys
    cfg_keys= [(cmd['key1'], cmd['key2'])
IndexError: list index out of range
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: IndexError: list index out of range
```

**Comment by Alexey-T** [comment]
new error
```
Python 3.8.10
Startup: 180ms, plugins: 0ms ()
Init: cuda_example_terminal
Init: cudatext
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 479, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
TypeError: 'NoneType' object is not iterable
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 479, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
TypeError: 'NoneType' object is not iterable
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 1232, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 247, in form_key_down
    if is_toggle_focus_hotkey(key, data):
  File "/home/user/cuda/cuda/app/py/cuda_example_terminal/terminal.py", line 479, in is_toggle_focus_hotkey
    for hotkey in get_hotkeys('toggle_focus'):
TypeError: 'NoneType' object is not iterable
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: TypeError: 'NoneType' object is not iterable
```

**Comment by veksha** [comment]
> when bottom-panel is docked, hotkeys are going to main form (Cud) , not to your form, so i guess you won't get on_key events

no. the problem is opposite. on_key events work normally (without them terminal cannot work).
when I return not False from on_key events I expect they go to Cud. but that not happens.

**Comment by veksha** [comment]
maybe it's failing for you because your folder is still "cuda_example_terminal".
there is a check in get_hotkeys: `cmd['p_module']=='cuda_exterminal'`

**Comment by veksha** [comment]
get latest fix and try again, please.

**Comment by veksha** [comment]
I would remove all this PROC_GET_COMMANDS  code if I will find the way to pass hotkeys to main Cud form from docked panel.

**Comment by Alexey-T** [comment]
IDK how to improve hotkeys yet
